config/routes.rb
Friendsnetwork::Application.routes.draw do

  get "users/search"
  
  

  devise_for :users, :controllers => { :registrations => "registrations"}

  resources :users do
    resources :profiles
    resources :friends
  end
  
  resources :posts do
   member do
    
   end
   collection do
     post 'add_comment'
     post 'add_like'
   end
   resources :comments
   resources :likes
  end 
  resources :friendlists do
    collection do
      get 'search_user'
      post 'add_friend'
      get 'check'
    end
    member do
      
    end
  end
  resources :homes
  resources :photos

   root :to => 'homes#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :post, :class_name=>'Post', :foreign_key=>'post_id'
  belongs_to :user, :class_name=>'User', :foreign_key=>'user_id'
  attr_accessible :comment, :post_id, :user_id
end

app/models/friendlist.rb
class Friendlist < ActiveRecord::Base

  belongs_to :user
  belongs_to :friend, :class_name => 'User', :foreign_key =>'friend_id'
  attr_accessible :friend_id, :status, :user_id, :update_attributes
  scope :current_friends, lambda { |user| where("status = 'accepted' and friend_id=?",user ) }
  scope :pending_requests, lambda { |user| where("status = 'pending' and user_id=?",user ) }
  scope :requested_friends, lambda { |user| where("status = 'requested' and user_id=?",user ) }
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to 'user', :class_name=>'User', :foreign_key=>'user_id'
  belongs_to 'post', :class_name=>'Post', :foreign_key=>'post_id'
  attr_accessible :post_id, :user_id
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :imagable, :polymorphic => true
  
  attr_accessible :imagable_id, :imagable_type, :image
  
  
  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
 
  belongs_to :user, :class_name => 'User', :foreign_key =>'sender_id'
  has_many :photos, :as => :imagable
  has_many :comments
  has_many :likes
  accepts_nested_attributes_for :photos
  accepts_nested_attributes_for :comments
  attr_accessible :message, :reciever_id, :sender_id, :share_with, :photos_attributes, :comments_attributes
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_one :photo, :as => :imagable
  accepts_nested_attributes_for :photo
  attr_accessible :education, :favourite_movie, :favourite_sport, :first_name, :hometown, :interested_in, :language, :last_name, :link, :location, :middle_name, :political, :quote, :relationship_status, :religion, :user_id, :website, :work,  :photo_attributes
end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :profile
  has_many :posts, :foreign_key =>'sender_id'
  has_many :comments
  has_many :likes
  has_many :friendlists, :dependent => :destroy
  has_many :friends, :through => :friendlists , :conditions => "status = 'accepted'"
  has_many :requested_friends, :through => :friendlists, :source => :user, :conditions => "status = 'requested'", :order => :created_at
  has_many :pending_friends, :through => :friendlists, :source => :user, :conditions => "status = 'pending'", :order => :created_at
  accepts_nested_attributes_for :profile
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  #  before_filter :authenticate_user!

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :birthdate, :email_id, :first_name, :gender, :last_name, :password, :profile_attributes, :photo_attributes
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def new
 end
 
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

#before_filter :login_required, :except => [:index, :show]

def index
 @user = User.find(params[:user_id])
 @current_friends = Friendlist.current_friends(current_user.id)
 @pending_requests = Friendlist.pending_requests(current_user.id)
 @requested_friends = Friendlist.requested_friends(current_user.id)
end

def show
redirect_to user_friend_path(params[:id])
end

def new

end

def create

end

def update

end

def destroy

end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def new
   
  end
  def index
 
  end
  def create
  
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
  
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
  end
  
  def index
   @post = Post.new
   @post.photos.build
   @posts = Post.order('created_at DESC')
  end
  
  def create
   @post = current_user.posts.build(params[:post])
    if(@post.save)
     redirect_to posts_path
    end
  end
  
  def show
  @post = Post.find
  end
  
  def add_comment
     @post=Post.find(params[:p_id])
     @comment = Comment.new(:post_id=>params[:p_id], :user_id=>current_user.id, :comment=>params[:text])
    #@comment = Comment.new(:post_id=>params[:id], :user_id=>current_user.id, :comment=>params[:comment])
    if(@comment.save)
      render :partial => 'comment'
    end
  end
  
  def add_like
  @post=Post.find(params[:p_id])
    @like = Like.new(:post_id=>params[:p_id], :user_id=>current_user.id)
    if(@like.save)
     render :partial => 'like'
    end 
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def create
   
  end 
  
  def index
   #@profile = Profile.all
  end
  
  def show
   @user =  User.includes(:profile).where(:id => params[:user_id]).first
   #@user = User.includes(:profile).where(:user_id => current_user.id)
  end
  
  def edit
    @user =  User.includes(:profile).where(:id => params[:user_id]).first
  end
  
  def update
  
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  def index
  end
  
  def edit
  @user = User.find(params[:id])
  end
  
  def create
    
  end
  
  def update
   
   @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
    redirect_to user_path(:id => current_user.id)
    flash[:success] = "Profile updated"
   end
  end
  
  def show
  @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

 def check_user(cur,frnd)
    @friendlist1 = Friendlist.new
    @friendlist2 = Friendlist.new
    @user = User.find(cur)
    @friend = User.find(frnd)
    @friendlist1 = Friendlist.find_by_user_id_and_friend_id(@user.id, @friend.id)
    @friendlist2 = Friendlist.find_by_user_id_and_friend_id(@friend.id, @user.id)
    if(@friendlist1.nil? or @friendlist2.nil?)
     return 1
    else
     return 0
    end 
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendlists_helper.rb
module FriendlistsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>

app/views/photos/show.html.erb
<h1>Upload photo</h1>

app/views/posts/_comment.html.erb
<div class="span11  well well-small">
    <%=image_tag @comment.user.profile.photo.image.small.url %>
      <strong><%= @comment.user.profile.first_name %>:</strong>
    <%= @comment.comment %><br>
</div>

app/views/posts/_index.html.erb
<%= form_for @post do |f| %>
    <%= f.label :Share_something %>
    
    <%= f.text_area :message, :id=>"text", :rows => 3, :class => "form-control", :style => "width: 649px" %>
    
    <div class="navbar navbar-fluid-top">
      <div class="span9 navbar-inner">Share photo
          <%= f.fields_for :photos do |photo| %>
          <%= photo.file_field :image %>
          <%end%>
          <div class="pull-right">
            <%= button_tag 'Share', :class => "btn btn-small", :id => "share" %>
          </div>
      </div>  
    </div>
<% end %>

app/views/posts/_like.html.erb
<strong><%= @like.user.profile.first_name %>:</strong>

app/views/posts/index.html.erb
<%= render :partial=> 'posts/index' %>

<br>
<% @posts.each do |post| %>
<br>
<div class="span9  well well-large">
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">
      <%=image_tag post.user.profile.photo.image.small.url%>
      <%= post.user.profile.first_name %>:</h3>
    </div>
    <div class="horizontalRule">
    </div>
    <%= post.message %><br>
    <%= image_tag post.photos.first.image.thumb.url rescue "" %><br><br>
    <div class="horizontalRule">
    </div><br>
      <% post.likes.each do |like| %>
          <strong><%= l.user.profile.first_name %>:</strong>
      <%end%>
      <div id="myspan1_<%= post.id%>">  
      </div>
      <div class="pull-right">
        <input type="button" value="like" id="<%= post.id%>" class="like_button" >
      </div>

      <div class="horizontalRule">
    </div><br>
    <% post.comments.each do |c| %>
      <div class="span11  well well-small">
            <%=image_tag c.user.profile.photo.image.small.url %>
             <strong><%= c.user.profile.first_name %>:</strong>
        <%= c.comment %><br>
      </div>
    <%end%>
    <div id="myspan_<%= post.id%>">
    
    </div>
    <div class="span11  well well-small">
      <%= image_tag current_user.profile.photo.image.small.url%>
      <%= current_user.profile.first_name %>
      <input type="text" id="box_<%= post.id%>" class="textbox" >
      <input type="button" value="comment" id="<%= post.id%>" class="button" >
  </div>
    
  </div>
</div>
<% end %>



<script type="text/javascript">

$(function(){
 $('.like_button').click(function(this){
 var id = (this.id);
 $.ajax({
 type: 'POST',
 url: 'posts/add_like',
 data: {p_id: id}
 }).done(function(ret){
   $(this).css('display','none');
   $('#myspan1_'+id).append(ret);
 });

 });
});

</script>

app/views/profiles/edit.html.erb
<h1>Edit form</h1>

<%=form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <%= f.fields_for :profile do |profile| %>
  
  <p>
    <%= profile.label :First_name %>
    <%= profile.text_field :first_name %>
  </p>
 
  <p>
  <%= profile.label :Middle_name %>
  <%= profile.text_field :middle_name %>  
  </p>
  
  <p>
  <%= profile.label :Last_name %>
  <%= profile.text_field :last_name %>  
  </p>
  
  <p>
  <%= profile.label :Language %>
  <%= profile.text_field :language %>  
  </p>
  
  <p>
  <%= profile.label :Link %>
  <%= profile.text_field :link %>  
  </p>
  
  <p>
  <%= profile.label :Hometown %>
  <%= profile.text_field :hometown %>  
  </p>
  
  <p>
  <%= profile.label :Location %>
  <%= profile.text_field :location %>  
  </p>
  
  <p>
  <%= profile.label :Interested_In %>
  <%= profile.text_field :interested_in %>  
  </p>
  
  <p>
  <%= profile.label :Political_View %>
  <%= profile.text_field :political %>  
  </p>
  
  <p>
  <%= profile.label :Favourite_Sport %>
  <%= profile.text_field :favourite_sport %>  
  </p>
  
  <p>
  <%= profile.label :Favourite_movie %>
  <%= profile.text_field :favourite_movie%>  
  </p>
  
  <p>
  <%= profile.label :Relationship_Status %>
  <%= profile.text_field :relationship_status %>  
  </p>
  
  <p>
  <%= profile.label :Religion %>
  <%= profile.text_field :religion %>  
  </p>
  
  <p>
  <%= profile.label :Work %>
  <%= profile.text_field :work %>  
  </p>
  
  <p>
  <%= profile.label :Education %>
  <%= profile.text_field :education %>  
  </p>
  
  <p>
  <%= profile.label :Website %>
  <%= profile.text_field :website %>  
  </p>
  
  <p>
  <%= profile.label :Quote %>
  <%= profile.text_field :quote %>  
  </p>
  
  <% end %>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/profiles/index.html.erb
<h1>Profiles#index</h1>
<h2>Users Profile</h2>


<table>
<tr>
<First Name>
</tr>
</table>

app/views/profiles/show.html.erb
<h1>User Profile</h1>



<table class="table table-condensed">
<tr>Name-</tr>
<tr class="success">
<td><%= @user.profile.first_name %></td>
<td><%= @user.profile.middle_name %></td>
<td><%= @user.profile.last_name %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Language-</tr>
<tr class="success">
<td><%= @user.profile.language %></td>
</tr>

<table class="table table-condensed">
<tr>Link-</tr>
<tr class="success">
<td><%= @user.profile.link %></td>

</tr>

<table class="table table-condensed">
<tr>Birthday-</tr>
<tr class="success">
<td><%= @user.birthdate %></td>
</tr>

<table class="table table-condensed">
<tr>Hometown-</tr>
<tr class="success">
<td><%= @user.profile.hometown %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Current Location-</tr>
<tr class="success">
<td><%= @user.profile.location %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Interested In-</tr>
<tr class="success">
<td><%= @user.profile.interested_in %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Political View-</tr>
<tr class="success">
<td><%= @user.profile.political %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Favourite Sport-</tr>
<tr class="success">
<td><%= @user.profile.favourite_sport %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Favourite Movie-</tr>
<tr class="success">
<td><%= @user.profile.favourite_movie %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Relationship Status-</tr>
<tr class="success">
<td><%= @user.profile.relationship_status %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Religion-</tr>
<tr class="success">
<td><%= @user.profile.religion %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Work-</tr>
<tr class="success">
<td><%= @user.profile.work %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Education-</tr>
<tr class="success">
<td><%= @user.profile.education %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Website-</tr>
<tr class="success">
<td><%= @user.profile.website %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Quote-</tr>
<tr class="success">
<td><%= @user.profile.quote %></td>
</tr>

</table>

<li><%= link_to "Edit", edit_user_profile_path(current_user)  %></li>

app/views/users/edit.html.erb
<h1>Edit form</h1><br>

<%=form_for @user do |f| %>
  
  <%= f.fields_for :profile do |profile| %>
  
  <p>
    <%= profile.label :First_name %>
    <%= profile.text_field :first_name %>
  </p>
 
  <p>
  <%= profile.label :Middle_name %>
  <%= profile.text_field :middle_name %>  
  </p>
  
  <p>
  <%= profile.label :Last_name %>
  <%= profile.text_field :last_name %>  
  </p>
  
  <p>
  <%= profile.label :Language %>
  <%= profile.text_field :language %>  
  </p>
  
  <p>
  <%= profile.label :Link %>
  <%= profile.text_field :link %>  
  </p>
  
  <p>
  <%= profile.label :Hometown %>
  <%= profile.text_field :hometown %>  
  </p>
  
  <p>
  <%= profile.label :Location %>
  <%= profile.text_field :location %>  
  </p>
  
  <p>
  <%= profile.label :Interested_In %>
  <%= profile.text_field :interested_in %>  
  </p>
  
  <p>
  <%= profile.label :Political_View %>
  <%= profile.text_field :political %>  
  </p>
  
  <p>
  <%= profile.label :Favourite_Sport %>
  <%= profile.text_field :favourite_sport %>  
  </p>
  
  <p>
  <%= profile.label :Favourite_movie %>
  <%= profile.text_field :favourite_movie%>  
  </p>
  
  <p>
  <%= profile.label :Relationship_Status %>
  <%= profile.text_field :relationship_status %>  
  </p>
  
  <p>
  <%= profile.label :Religion %>
  <%= profile.text_field :religion %>  
  </p>
  
  <p>
  <%= profile.label :Work %>
  <%= profile.text_field :work %>  
  </p>
  
  <p>
  <%= profile.label :Education %>
  <%= profile.text_field :education %>  
  </p>
  
  <p>
  <%= profile.label :Website %>
  <%= profile.text_field :website %>  
  </p>
  
  <p>
  <%= profile.label :Quote %>
  <%= profile.text_field :quote %>  
  </p>
  
  <%= profile.fields_for :photo do |photo| %>
    <p>
     <%= photo.label :Change_profile_picture %>
     <%= photo.file_field :image %>
    </p>
   <% end %>
  
  
  <% end %>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1>user index</h1>

app/views/users/login.html.erb
<h1>LogIn Here</h1>

<%= form_for :user, :url => user_path do |f| %>
  <p>
    <%= f.label :Username %><br>
    <%= f.text_field :email_id %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_field :password %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>


#<%= link_to 'Back', posts_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div>

</div>

<div>
<table class="table table-condensed">
<tr>Name-</tr>
<tr class="success">
<td><%= @user.profile.first_name %></td>
<td><%= @user.profile.middle_name %></td>
<td><%= @user.profile.last_name %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Language-</tr>
<tr class="success">
<td><%= @user.profile.language %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Link-</tr>
<tr class="success">
<td><%= @user.profile.link %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Birthday-</tr>
<tr class="success">
<td><%= @user.birthdate %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Hometown-</tr>
<tr class="success">
<td><%= @user.profile.hometown %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Current Location-</tr>
<tr class="success">
<td><%= @user.profile.location %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Interested In-</tr>
<tr class="success">
<td><%= @user.profile.interested_in %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Political View-</tr>
<tr class="success">
<td><%= @user.profile.political %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Favourite Sport-</tr>
<tr class="success">
<td><%= @user.profile.favourite_sport %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Favourite Movie-</tr>
<tr class="success">
<td><%= @user.profile.favourite_movie %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Relationship Status-</tr>
<tr class="success">
<td><%= @user.profile.relationship_status %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Religion-</tr>
<tr class="success">
<td><%= @user.profile.religion %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Work-</tr>
<tr class="success">
<td><%= @user.profile.work %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Education-</tr>
<tr class="success">
<td><%= @user.profile.education %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Website-</tr>
<tr class="success">
<td><%= @user.profile.website %></td>
</tr>
</table>

<table class="table table-condensed">
<tr>Quote-</tr>
<tr class="success">
<td><%= @user.profile.quote %></td>
</tr>

</table>
</div>
<li><%= link_to "Edit", edit_user_path(current_user)  %></li>