config/routes.rb
Friendsnetwork::Application.routes.draw do

  get "users/search"
  
  

  devise_for :users, :controllers => { :registrations => "registrations"}

  resources :users do
    resources :profiles
    resources :friends
  end
  
  resources :posts do
   member do
    
   end
   collection do
     post 'add_comment'
     post 'add_like'
   end
   resources :comments
   resources :likes
  end 
  resources :friendlists do
    collection do
      get 'search_user'
      post 'add_friend'
      get 'check'
    end
    member do
      
    end
  end
  resources :homes
  resources :photos

   root :to => 'homes#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  
  belongs_to :post, :class_name=>'Post', :foreign_key=>'post_id'
  belongs_to :user, :class_name=>'User', :foreign_key=>'user_id'
  attr_accessible :comment, :post_id, :user_id
end

app/models/friendlist.rb
class Friendlist < ActiveRecord::Base

  belongs_to :user
  belongs_to :friend, :class_name => 'User', :foreign_key =>'friend_id'
  attr_accessible :friend_id, :status, :user_id, :update_attributes
  scope :current_friends, lambda { |user| where("status = 'accepted' and friend_id=?",user ) }
  scope :pending_requests, lambda { |user| where("status = 'pending' and user_id=?",user ) }
  scope :requested_friends, lambda { |user| where("status = 'requested' and user_id=?",user ) }
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to 'user', :class_name=>'User', :foreign_key=>'user_id'
  belongs_to 'post', :class_name=>'Post', :foreign_key=>'post_id'
  attr_accessible :post_id, :user_id
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :imagable, :polymorphic => true
  
  attr_accessible :imagable_id, :imagable_type, :image
  
  
  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
 
  belongs_to :user, :class_name => 'User', :foreign_key =>'sender_id'
  has_many :photos, :as => :imagable
  has_many :comments
  has_many :likes
  accepts_nested_attributes_for :photos
  accepts_nested_attributes_for :comments
  attr_accessible :message, :reciever_id, :sender_id, :share_with, :photos_attributes, :comments_attributes
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_one :photo, :as => :imagable
  accepts_nested_attributes_for :photo
  attr_accessible :education, :favourite_movie, :favourite_sport, :first_name, :hometown, :interested_in, :language, :last_name, :link, :location, :middle_name, :political, :quote, :relationship_status, :religion, :user_id, :website, :work,  :photo_attributes
end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :profile
  has_many :posts, :foreign_key =>'sender_id'
  has_many :comments
  has_many :likes
  has_many :friendlists, :dependent => :destroy
  has_many :friends, :through => :friendlists , :conditions => "status = 'accepted'"
  has_many :requested_friends, :through => :friendlists, :source => :user, :conditions => "status = 'requested'", :order => :created_at
  has_many :pending_friends, :through => :friendlists, :source => :user, :conditions => "status = 'pending'", :order => :created_at
  accepts_nested_attributes_for :profile
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  #  before_filter :authenticate_user!

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :birthdate, :email_id, :first_name, :gender, :last_name, :password, :profile_attributes, :photo_attributes
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def new
   
  end
  def index
 
  end
  def create
  
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
  
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
  end
  
  def index
   @post = Post.new
   @post.photos.build
   @posts = Post.order('created_at DESC')
  end
  
  def create
   @post = current_user.posts.build(params[:post])
    if(@post.save)
     redirect_to posts_path
    end
  end
  
  def show
  @post = Post.find
  end
  
  def add_comment
     @post=Post.find(params[:p_id])
     @comment = Comment.new(:post_id=>params[:p_id], :user_id=>current_user.id, :comment=>params[:text])
    #@comment = Comment.new(:post_id=>params[:id], :user_id=>current_user.id, :comment=>params[:comment])
    if(@comment.save)
      render :partial => 'comment'
    end
  end
  
  def add_like
  @post=Post.find(params[:p_id])
    @like = Like.new(:post_id=>params[:p_id], :user_id=>current_user.id)
    if(@like.save)
     render :partial => 'like'
    end 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  def index
  end
  
  def edit
  @user = User.find(params[:id])
  end
  
  def create
    
  end
  
  def update
   
   @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
    redirect_to user_path(:id => current_user.id)
    flash[:success] = "Profile updated"
   end
  end
  
  def show
  @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

 def check_user(cur,frnd)
    @friendlist1 = Friendlist.new
    @friendlist2 = Friendlist.new
    @user = User.find(cur)
    @friend = User.find(frnd)
    @friendlist1 = Friendlist.find_by_user_id_and_friend_id(@user.id, @friend.id)
    @friendlist2 = Friendlist.find_by_user_id_and_friend_id(@friend.id, @user.id)
    if(@friendlist1.nil? or @friendlist2.nil?)
     return 1
    else
     return 0
    end 
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendlists_helper.rb
module FriendlistsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Friendsnetwork" %></title>
    <%= csrf_meta_tags %>
    
 <%= javascript_include_tag "application" %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Friendsnetwork</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% if current_user.present? %>
              <li><%= link_to "Home", posts_path  %></li>
              <li><%= link_to "Profile", user_path(:id => current_user.id) %></li>
              <li><%= link_to "Friends", user_friends_path(:user_id => current_user.id) %></li>
              <li><%= link_to "Search Friends", friendlists_path %></li>
              <% end %>
            </ul>
            
            <div class="pull-right">
              <ul class="nav">
              <% if current_user.present? %>
                <li><%= link_to 'sign-out', destroy_user_session_path, :method => :delete %></li>
                <% end %>
                <% if !current_user.present? %>
                <li><%= link_to 'Sign-in', user_session_path %></li>
                <% end %>
                </ul>
              </div>
            
          </div><!--/.nav-collapse -->
           
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <% if current_user.present? %>
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header"><h3>
                <%= current_user.profile.first_name %></h3></li>
                
              <%= image_tag current_user.profile.photo.image.thumb.url %><br><br>
              <li><%= link_to "Home", posts_path %></li>
              <li><%= link_to "Profile", user_path(:id => current_user.id) %></li>
              <li><%= link_to "Friends", user_friends_path(:user_id => current_user.id) %></li>
              <li><%= link_to "Search Friends", friendlists_path %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
         <% end %>
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
   
    

  </body>
</html>